# Generated by Django 5.1.4 on 2025-08-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField(default=datetime.datetime.now)),
                ('check_out', models.DateTimeField(default=datetime.datetime.now)),
                ('guest_name', models.CharField(max_length=100)),
            ],
        ),
    ]
