# Generated by Django 5.1.4 on 2025-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
