# Generated by Django 5.1.4 on 2025-08-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_guest_name', models.CharField(max_length=100)),
                ('new_guest_name', models.CharField(max_length=100)),
                ('old_check_in_date', models.DateField()),
                ('old_check_out_date', models.DateField()),
                ('new_check_in_date', models.DateField()),
                ('new_check_out_date', models.DateField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=150)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.booking')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.CharField(max_length=150)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.room')),
            ],
        ),
    ]
