# Generated by Django 5.1.4 on 2025-08-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_changedbookings_deletedbookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=150)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='ChangedBookings',
        ),
    ]
