# Generated by Django 5.1.4 on 2025-08-10 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_room_check_in_remove_room_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='room',
            name='guest_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
