# Generated by Django 5.1.4 on 2025-08-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_addedbookings_delete_changedbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedbookings',
            name='booking',
        ),
        migrations.AddField(
            model_name='addedbookings',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tables.room'),
        ),
    ]
