# Generated by Django 5.1.4 on 2025-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_room_check_in_room_check_out_room_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
