# Generated by Django 5.1.4 on 2025-08-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_remove_addedbookings_booking_addedbookings_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.CharField(default='idk', max_length=100),
        ),
    ]
