# Generated by Django 5.1.4 on 2025-08-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_room_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
    ]
