# Generated by Django 5.1.4 on 2025-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_room_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
